// src/mepal/kuoAVDoble/parts/kuoAVDobleParts.js
// ─────────────────────────────────────────────────────────────────────────────
// Catálogo de partes y roles para Puesto Doble KUO AV
// ─────────────────────────────────────────────────────────────────────────────

export const KUO_AV_DOBLE_PART_ROLES = Object.freeze({
  SURFACE_FRONT: 'SURFACE_FRONT',
  SURFACE_BACK: 'SURFACE_BACK',
  SUPPORT_LEFT: 'SUPPORT_LEFT',
  SUPPORT_RIGHT: 'SUPPORT_RIGHT',
  SUPPORT_INTERMEDIATE: 'SUPPORT_INTERMEDIATE',
  BEAM_FRONT: 'BEAM_FRONT',
  BEAM_BACK: 'BEAM_BACK',
  DOUBLE_DUCT: 'DOUBLE_DUCT',
  GROMMET_LEFT: 'GROMMET_LEFT',
  GROMMET_RIGHT: 'GROMMET_RIGHT',
  POWER_KIT_LEFT: 'POWER_KIT_LEFT',
  POWER_KIT_RIGHT: 'POWER_KIT_RIGHT',
  POWER_OUTLET_LEFT: 'POWER_OUTLET_LEFT',
  POWER_OUTLET_RIGHT: 'POWER_OUTLET_RIGHT',
  VERTEBRA_LEFT: 'VERTEBRA_LEFT',
  VERTEBRA_RIGHT: 'VERTEBRA_RIGHT',
  BUTTONS: 'BUTTONS',
  BALDOSA: 'BALDOSA',
  PANTALLA: 'PANTALLA',
});

export const KUO_AV_DOBLE_PARTS = Object.freeze({
  SURFACE_FRONT: {
    code: 'LKSU010010_F',
    lookupTag: 'LKSU010010',
    name: 'Superficie Perimetral Frontal',
    role: KUO_AV_DOBLE_PART_ROLES.SURFACE_FRONT,
    type: 'superficie',
    modelKind: 'procedural',
  },
  SURFACE_BACK: {
    code: 'LKSU010010_P',
    lookupTag: 'LKSU010010',
    name: 'Superficie Perimetral Posterior',
    role: KUO_AV_DOBLE_PART_ROLES.SURFACE_BACK,
    type: 'superficie',
    modelKind: 'procedural',
  },
  BEAM_FRONT: {
    code: 'KUSO420000_F',
    lookupTag: 'KUSO420000',
    name: 'Viga Soporte Frontal',
    role: KUO_AV_DOBLE_PART_ROLES.BEAM_FRONT,
    type: 'viga',
    modelKind: 'glb',
  },
  BEAM_BACK: {
    code: 'KUSO420000_P',
    lookupTag: 'KUSO420000',
    name: 'Viga Soporte Posterior',
    role: KUO_AV_DOBLE_PART_ROLES.BEAM_BACK,
    type: 'viga',
    modelKind: 'glb',
  },
  DOUBLE_DUCT: {
    code: 'KUSO830000',
    lookupTag: 'KUSO830000',
    name: 'Ducto Central Doble',
    role: KUO_AV_DOBLE_PART_ROLES.DOUBLE_DUCT,
    type: 'ducto',
    modelKind: 'glb',
  },
  SUPPORT_LEFT: {
    code: 'KUSO820000_IZQ',
    lookupTag: 'KUSO820000',
    name: 'Costado Doble Izquierdo',
    role: KUO_AV_DOBLE_PART_ROLES.SUPPORT_LEFT,
    type: 'costado',
    modelKind: 'glb',
  },
  SUPPORT_RIGHT: {
    code: 'KUSO820000_DER',
    lookupTag: 'KUSO820000',
    name: 'Costado Doble Derecho',
    role: KUO_AV_DOBLE_PART_ROLES.SUPPORT_RIGHT,
    type: 'costado',
    modelKind: 'glb',
  },
  SUPPORT_INTERMEDIATE: {
    code: 'KUSO820000_INT',
    lookupTag: 'KUSO820000',
    name: 'Costado Intermedio Doble',
    role: KUO_AV_DOBLE_PART_ROLES.SUPPORT_INTERMEDIATE,
    type: 'costado',
    modelKind: 'glb',
  },
  GROMMET_DOUBLE: {
    code: 'LKAC250000_DOBLE',
    lookupTag: 'LKAC250000',
    name: 'Grommet Doble Abatible',
    role: KUO_AV_DOBLE_PART_ROLES.GROMMET_LEFT,
    type: 'grommet',
    modelKind: 'glb',
  },
  SOCKET_SUPPORT_FRONT: {
    code: 'KUAC680000_F',
    lookupTag: 'KUAC680000',
    name: 'Soporte Tomas Frontal',
    role: KUO_AV_DOBLE_PART_ROLES.POWER_OUTLET_LEFT,
    type: 'soporte_tomas',
    modelKind: 'glb',
  },
  SOCKET_SUPPORT_BACK: {
    code: 'KUAC680000_P',
    lookupTag: 'KUAC680000',
    name: 'Soporte Tomas Posterior',
    role: KUO_AV_DOBLE_PART_ROLES.POWER_OUTLET_RIGHT,
    type: 'soporte_tomas',
    modelKind: 'glb',
  },
  POWER_KIT_DOUBLE: {
    code: 'KUAC1040000_74Doble',
    lookupTag: 'KUAC1040000',
    name: 'Kit Fuente Doble Central',
    role: KUO_AV_DOBLE_PART_ROLES.POWER_KIT_LEFT,
    type: 'kit_fuente',
    modelKind: 'glb',
  },
  VERTEBRA_LEFT: {
    code: '22000116690',
    lookupTag: 'KUAC650000',
    name: 'Vértebra Pasacables Izquierda',
    role: KUO_AV_DOBLE_PART_ROLES.VERTEBRA_LEFT,
    type: 'vertebra',
    modelKind: 'glb',
  },
  VERTEBRA_RIGHT: {
    code: '22000116690',
    lookupTag: 'KUAC650000',
    name: 'Vértebra Pasacables Derecha',
    role: KUO_AV_DOBLE_PART_ROLES.VERTEBRA_RIGHT,
    type: 'vertebra',
    modelKind: 'glb',
  },
  BUTTON_FRONT: {
    code: 'DPBK06_F',
    lookupTag: 'DPBK06',
    name: 'Botonera Control Frontal',
    role: KUO_AV_DOBLE_PART_ROLES.BUTTONS,
    type: 'control',
    modelKind: 'logical',
  },
  BUTTON_BACK: {
    code: 'DPBK06_P',
    lookupTag: 'DPBK06',
    name: 'Botonera Control Posterior',
    role: KUO_AV_DOBLE_PART_ROLES.BUTTONS,
    type: 'control',
    modelKind: 'logical',
  },
  BALDOSA: {
    code: 'KUBAL01',
    lookupTag: 'KUBAL01',
    name: 'Baldosa Divisoria Central',
    role: KUO_AV_DOBLE_PART_ROLES.BALDOSA,
    type: 'accesorio',
    modelKind: 'procedural',
  },
});

export default KUO_AV_DOBLE_PARTS;
