export { LINK_FINISH_OPTIONS, LINK_FINISH_CODES, LINK_SURFACE_POSITION_CODES, LINK_INTEGRACION_INDIVIDUAL_CODES, LINK_INTEGRACION_DOBLE_CODES, LINK_SUPPORT_SHAPES, getLinkFinishOptions } from '../catalog/linkFinishCatalog.js';

