export const CONSTRAINT_TYPES = Object.freeze({
  COINCIDENT: 'COINCIDENT',
  ALIGN_HORIZONTAL: 'ALIGN_HORIZONTAL',
  ALIGN_VERTICAL: 'ALIGN_VERTICAL',
  DISTANCE: 'DISTANCE',
  PARALLEL: 'PARALLEL',
  PERPENDICULAR: 'PERPENDICULAR',
});

